---
# tasks file for ansible-common

- hostname:
    name: "{{ inventory_hostname }}"
  when: common_reset_hostname

- name: Add ip addr to hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.ip }}\s+'
    line: "{{ item.ip}}    {{item.name}}"
    owner: root
    group: root
    mode: 0644
    unsafe_writes: True
  when: common_hosts | length > 0
  with_items: "{{ common_hosts }}"

- name: Activate EPEL repo
  yum:
    name: epel-release
    state: present
  when: common_epel_enable

- name: Install common packages
  yum:
    name: "{{ common_packages }}"
    state: present
  when: common_packages | length > 0

- import_tasks: firewalld.yml
  when: common_firewalld_enable
