---
- name: Add User
  user: name={{item.user}} shell="{{item.shell}}"
  become: true
  with_items:
  - "{{ common_users }}"

- name: Add user keys
  authorized_key: user={{ item.user }} key="{{ item.key }}"
  become: true
  with_items:
  - "{{ common_users }}"

- name: Add sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ item.user }} ALL="
    line: "{{ item.user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  become: true
  when: item.sudo is defined and item.sudo
  with_items:
  - "{{ common_users }}"